<br>
<table cellSpacing="0" cellPadding="0" border="0">
  <tr>
    <td><div style="PADDING-LEFT: 0px; OVERFLOW: hidden; WIDTH: 133px"><font
    style="FONT-SIZE: 13px" face="arial,sans-serif" color="#0000ff"><a
    href="http://www.seiretto.com/web_hosting/reseller_hosting.php"><b>
<p>UK reseller hosting</b></a></font><font style="FONT-SIZE: 13px" face="arial,sans-serif" color="#000000"><br>
start your own web reseller business </font><font style="FONT-SIZE: 10px"
    face="arial,sans-serif" color="#008000">Seiretto.com</font></p>
    </div></td>
  </tr>
</table>
<br>

<table cellSpacing="0" cellPadding="0" border="0">
  <tr>
    <td><div style="PADDING-LEFT: 0px; OVERFLOW: hidden; WIDTH: 133px"><font
    style="FONT-SIZE: 13px" face="arial,sans-serif" color="#0000ff"><a
    href="http://www.AcHost.co.uk/"><b>
<p>ac.uk web hosting</b></a><br>
    </font><font style="FONT-SIZE: 13px" face="arial,sans-serif" color="#000000">
UK academic domain names and web hosting<br></font><font style="FONT-SIZE: 10px"
    face="arial,sans-serif" color="#008000">AcHost.co.uk</font></p>
    </div></td>
  </tr>
</table>
<br>

<table cellSpacing="0" cellPadding="0" border="0">
  <tr>
    <td>
	&nbsp;</td>
  </tr>
</table>